# -*- coding: utf-8 -*-
"""loan_rate_by_age_income.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xl5D_UVLbA7sNroCxTf7zhuID4I0fkQH
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv('age_income_loan.csv')
df.head()

df['income'] = df['income'].replace('[\$,]', '', regex=True).astype(float)

df = df[(df['age'] >= 18) & (df['age'] <= 100)]

df = df.dropna(subset=['age', 'income', 'personal_loan'])

df.head()

df.describe()

age_bins = [20, 30, 40, 50, 60, 70]
age_labels = ['20-29', '30-39', '40-49', '50-59', '60-69']
df['age_group'] = pd.cut(df['age'], bins=age_bins, labels=age_labels)

income_bins = [0, 30, 60, 90, 120, 150, 250]
income_labels = ['<30k', '30-60k', '60-90k', '90-120k', '120-150k', '150k+']
df['income_group'] = pd.cut(df['income'], bins=income_bins, labels=income_labels)

age_rate = df.groupby('age_group')['personal_loan'].mean().reset_index()
age_rate.rename(columns={'personal_loan': 'loan_rate'}, inplace=True)

income_rate = df.groupby('income_group')['personal_loan'].mean().reset_index()
income_rate.rename(columns={'personal_loan': 'loan_rate'}, inplace=True)

combo_rate = df.groupby(['age_group', 'income_group'])['personal_loan'].mean().reset_index()
combo_rate.rename(columns={'personal_loan': 'loan_rate'}, inplace=True)

age_order_map = { '20-29': 1, '30-39': 2, '40-49': 3, '50-59': 4, '60-69': 5 }
income_order_map = { '<30k': 1, '30-60k': 2, '60-90k': 3, '90-120k': 4, '120-150k': 5, '150k+': 6 }

combo_rate['age_order'] = combo_rate['age_group'].map(age_order_map)
combo_rate['income_order'] = combo_rate['income_group'].map(income_order_map)

combo_rate = combo_rate.sort_values(by=['age_order', 'income_order'])

print(combo_rate)

combo_rate.to_csv('loan_rate_by_age_income.csv', index=False)